### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by zhanghongruiupup** [L1aoXingyu/reid_baseline#31]
error:module 'tensorflow._api.v1.io' has no attribute 'gfile'
hope your reply.

**Comment by L1aoXingyu** [comment]
can you screen snap the problem in which file and which line?

**Comment by zhanghongruiupup** [comment]
> can you screen snap the problem in which file and which line?

/home/fwq/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "tools/train.py", line 75, in <module>
    main()
  File "tools/train.py", line 57, in main
    writer = SummaryWriter(os.path.join(log_save_dir, 'tf'))
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 221, in __init__
    self._get_file_writer()
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 252, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 62, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/tensorboard/summary/writer/event_file_writer.py", line 73, in __init__
    if not tf.io.gfile.exists(logdir):
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'

**Comment by zhanghongruiupup** [comment]
> can you screen snap the problem in which file and which line?

train_openset.sh　　

GPUS='0'

CUDA_VISIBLE_DEVICES=$GPUS python tools/train.py -cfg='configs/softmax_triplet.yml' \
DATASETS.NAMES '("market1501",)'  \
DATASETS.TEST_NAMES 'market1501' \
INPUT.SIZE_TRAIN '[256, 128]' \
INPUT.SIZE_TEST '[256, 128]' \
SOLVER.IMS_PER_BATCH '256' \
MODEL.NAME 'baseline' \
MODEL.WITH_IBN 'True' \
MODEL.BACKBONE 'resnet50' \
MODEL.VERSION 'baseline_bs256' \
MODEL.PRETRAIN_PATH '/home/fwq/zhanghongruils/bag of trick/ibn-gcnet/resnet50_ibn_a.pth.tar' \
SOLVER.OPT 'adam' \
SOLVER.LOSSTYPE '("softmax", "triplet")' \
