### ISSUE TITLE
KeyError: 'classifier.weight'

### ISSUE THREAD

**Issue by cendelian** [L1aoXingyu/reid_baseline#37]
WEIGHT: /home/cendelian/Study_CV/车辆检测/reid_baseline/save/trained_model/path/resnet101_ibn_a.pth.tar
Traceback (most recent call last):
  File "tools/test.py", line 61, in <module>
    main()
  File "tools/test.py", line 53, in main
    model.load_params_wo_fc(torch.load(cfg.TEST.WEIGHT))
  File "./modeling/baseline.py", line 63, in load_params_wo_fc
    state_dict.pop('classifier.weight')
**KeyError: 'classifier.weight'**

请问这是什么错误呢？
我运行
`sh test_model.sh `
的以上错误

**Comment by L1aoXingyu** [comment]
你的model是不是修改过了，里面没有`classifier.weight` 这个参数
